### ISSUE TITLE
CSV example download link is wrong

### ISSUE THREAD

**Issue by cojofra** [autodesk-bionano/genome-designer#1007]
with the recent doc change I forgot to update that link
documentation is here: https://geneticconstructor.readme.io/v1.0/docs/csv-upload
csv is here: https://drive.google.com/file/d/0B59XgjZRlAfIVDFjdFhoRjRDV0U/view?usp=sharing

also the wording+link from the general csv import should be added to the list block csv import

**Comment by maxbates** [comment]
@cojofra are you going to take care of this?

**Comment by maxbates** [comment]
file probably called ImportCsvModal or something

**Comment by cojofra** [comment]
looking right now.
shot my local install - so getting myself testing locally again is some more work.
