### ISSUE TITLE
UX Spec: History

### ISSUE THREAD

**Issue by jlachoff** [autodesk-bionano/genome-designer#142]
A researcher using the software can:
* Access previous versions of a construct, so they can see how it evolved to it's current state;
* Restore a previous version of a construct to be the current version, so there is no "penalty" for exploring design ideas;
* Undo edits made during the current editing session, so there is no "penalty" for exploring design ideas;
* See a read-only version of a construct **as specified,** once sent to the foundry, so there is no question as to what was requested;
* See another read-only version of a construct **as built,** once the foundry process is completed, along with any results data, so they can make informed decisions about next steps in their research.
* View a construct specified for building in the foundry with the edits made between versions visually emphasized, so they can tell at a glance what has been specified to be changed when the construct is built.
* Compare any two constructs (or versions of a construct), highlighting differences, so they can tell what is different in a simple way.
* Create alternative views of a project with any subset of the project's content they find suitable for their publication goal, so they can share their research with a diversity of audiences without resorting to workarounds.

**Comment by dchandran** [comment]
Some items, such as comparing two constructs, is a lot of work; we should not tackle it unless necessary.

For now, the document that Joe created with the different terms is good conclusion to this issue. https://docs.google.com/document/d/1QkmS0k5jz3fGxjsuUNGuhkh_pRjEJsOS4NoLqsO82Ko/edit?usp=sharing
