### ISSUE TITLE
Pros and cons of Onion as a plugin vs Onion as a platform app

### ISSUE THREAD

**Issue by autodesk-bionano** [autodesk-bionano/genome-designer#16]
Define what a plugin API would allow and now allow

**Comment by IsaacLuo** [comment]
Maybe we can do it in both ways. So, how about that, Onion is an application which has some plugins (plasmid viewer, dna editor, etc.) any other page can embed one or more plugins of onion by giving a DOM and plasmid data, and call onion's backend APIs if needed. Or, other page can directly export data to onion application in an iframe or another window.

**Comment by dchandran** [comment]
This is a more general question that applies to all plugins/extensions (different issue). We don't need a specific discussion for Onion.
