### ISSUE TITLE
(UX-inventory) How to add items to My Inventory

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#181]
Inventory can be populated using:
1) sequence text (copy-paste)
2) genbank file
      a) use genbank file as a single item
      b) use all features inside a genbank file as separate items
3) fasta file
       a) fasta file can have multiple sequences

**Comment by jlachoff** [comment]
Can we re-label this as, "How to add items to My Inventory"? If your intent is to allow users to populate their inventories using these methods, we should be clear that the specific inventory being populated is the user's personal inventory.
