### ISSUE TITLE
UX spec: nested constructs

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#29]
A researcher using the software needs the ability to create hierarchical structure in larger designs so that they can easily manage the large amount of information in an organized fashion.

**Comment by jlachoff** [comment]
See section "Nesting Content" in "UX Spec - Constructs" for spec: https://docs.google.com/document/d/1btzsAo-fOr-koLaq6gMkjVjqCOSX8Xizhayeioq4DZo/edit#heading=h.ikkpx0ino17
