### ISSUE TITLE
UX spec: instances of a template

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#32]
A researcher using the software wants to specify multiple variations of the first instance of construct, effectively using the first instance as a "template". The researcher wants the flexibility to update the template even after some instances are created, and have the instances be updated to reflect changes in the template.

**Comment by jlachoff** [comment]
Moving to Sprint 3, as I did not get to this story in Sprint 2.

**Comment by jlachoff** [comment]
Moving to Sprint 5, with the expectation that this design work will be needed in the Feb MVP release.

**Comment by jlachoff** [comment]
Moving to Sprint 6.
