### ISSUE TITLE
UX spec: Combinatorial blocks with multiple parts

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#33]
A researcher using the software needs to be able to specify a list of alternative blocks for any block.

**Comment by jlachoff** [comment]
The design work to do here is to make sure we can accommodate the combinatorial feature when the time comes.

**Comment by jlachoff** [comment]
See spec: https://docs.google.com/document/d/1btzsAo-fOr-koLaq6gMkjVjqCOSX8Xizhayeioq4DZo/edit#heading=h.a1xycp4bapkq

Closing out this issue as the current level of design work accomplished the main goal for this sprint, which was to explore the feature sufficiently to validate our overall design approach to constructs won't be incompatible with the feature when we do implement it.
