### ISSUE TITLE
UX spec: Navigation and command access

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#34]
Specify contextual menus and global navigation.

**Comment by jlachoff** [comment]
See "UX Spec - Menus and Commands" https://drive.google.com/open?id=1YnjA9HOLIrFpxswsVtvxvCe4JP7iRAwcIwj7_C0q0H8

**Comment by jlachoff** [comment]
More work to come in future sprints, but this should be enough to get us going.
