### ISSUE TITLE
UX spec: SBOL block typing

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#35]
If a block is assigned a single SBOL symbol, the block should be represented as that symbol "type" in the construct.

**Comment by jlachoff** [comment]
In the future, we may make it possible to toggle between block name and symbol views.

**Comment by jlachoff** [comment]
See section in Constructs spec: https://docs.google.com/document/d/1btzsAo-fOr-koLaq6gMkjVjqCOSX8Xizhayeioq4DZo/edit#heading=h.u6jdymbp2ocn
