### ISSUE TITLE
UX spec: deleting regions of a larger Block

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#49]
As a researcher using the software, I commonly need to specify that a genetic sequence in my design is to be created by using only a portion of an existing sequence.

**Comment by jlachoff** [comment]
UX Spec: 2 consecutive sections in the Constructs spec:

https://docs.google.com/document/d/1btzsAo-fOr-koLaq6gMkjVjqCOSX8Xizhayeioq4DZo/edit#heading=h.ivniwhgso0

https://docs.google.com/document/d/1btzsAo-fOr-koLaq6gMkjVjqCOSX8Xizhayeioq4DZo/edit#heading=h.kj7qgv3s4c1l
