### ISSUE TITLE
Implement data structures

### ISSUE THREAD

**Issue by autodesk-bionano** [autodesk-bionano/genome-designer#5]
Implement data structures (schema) using own validation (and potentially graphQL)

Data structures needed for:
Project, Construct, Part, Inventory, History, Author (user?), Metadata, etc..

**Comment by maxbates** [comment]
I've punted on GraphQL for now because it's unclear if we're going to use it. Also need to determine whether validation is going to happen on the client. If it is, we need to separate GraphQL from what is bundled for the client, so its not sent over the wire
