### ISSUE TITLE
UX spec: replacing a region of a large block with a new block

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#50]
As a researcher using the software, I need my high level design representation to accurately communicate when deletions and replacements, which are common in the experiments I run, are intended during a build.

**Comment by jlachoff** [comment]
UX Spec: 2 consecutive sections in the Constructs spec:

https://docs.google.com/document/d/1btzsAo-fOr-koLaq6gMkjVjqCOSX8Xizhayeioq4DZo/edit#heading=h.ivniwhgso0

https://docs.google.com/document/d/1btzsAo-fOr-koLaq6gMkjVjqCOSX8Xizhayeioq4DZo/edit#heading=h.kj7qgv3s4c1l
