### ISSUE TITLE
Server code (NodeJS) with basic data set/get capabilities

### ISSUE THREAD

**Issue by autodesk-bionano** [autodesk-bionano/genome-designer#6]
The server should be able to get/set data for the default user. Data refers to Projects, Constructs, Parts, Inventory, History, etc.

**Comment by maxbates** [comment]
So basically we're saying we want a basic database, with things saved / accessible by ID, with some indexing? Probably some notion of permissions / users? Really simple to start? @dchandran we should talk about this?

**Comment by maxbates** [comment]
there is a route `/api` that delegates to an express router in the folder `/api/` -- otherwise delegates to client routing

**Comment by maxbates** [comment]
I'm going to close this in favor of #74 and #72 and given the above work. in the future, when we need a database ,we can add relevant issues but this is too monolithic as is
