### ISSUE TITLE
Components don't get rendered

### ISSUE THREAD

**Issue by QuteBits** [autodesk-bionano/genome-designer#623]
npm install | npm run start
then got to "By Kind", "Promoter (7)" - so far so good - then click on "CAGp" and I get this error:

**http://localhost:3001/project/project-80cb62fa-c7d3-41a1-b84d-8e771438a6e8**

	INSPECTOR

	TypeError: instances[0].isList is not a function
	InspectorBlock.render
	/.../genome-designer/src/components/Inspector/InspectorBlock.js
	InspectorBlock.tryRender
	http://localhost:3001/static/client.js:828:32
	InspectorBlock.proxiedMethod
	http://localhost:3001/static/client.js:94695:31
	ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
	http://localhost:3001/static/client.js:97661:35
	ReactCompositeComponentWrapper._renderValidatedComponent
	http://localhost:3001/static/client.js:97681:33
	ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent]
	http://localhost:3001/static/client.js:22686:22
	ReactCompositeComponentWrapper._updateRenderedComponent
	http://localhost:3001/static/client.js:97634:37
	ReactCompositeComponentWrapper._performComponentUpdate
	http://localhost:3001/static/client.js:97618:11
	ReactCompositeComponentWrapper.updateComponent
	http://localhost:3001/static/client.js:97547:13
	ReactCompositeComponentWrapper.wrapper [as updateComponent]
	http://localhost:3001/static/client.js:22686:22
	ReactCompositeComponentWrapper.receiveComponent
	http://localhost:3001/static/client.js:97479:11
	Object.receiveComponent
	http://localhost:3001/static/client.js:28499:23

**Comment by maxbates** [comment]
Sorry for the radio silence -- this has been fixed in #632

**Comment by QuteBits** [comment]
awesome, thanks man
