### ISSUE TITLE
Decide appropriate front-end technology: Canvas or SVG?

### ISSUE THREAD

**Issue by autodesk-bionano** [autodesk-bionano/genome-designer#7]
Canvas or SVG? List pros and cons for the purpose of this project.

**Comment by maxbates** [comment]
@duncanmeech would like you to weigh in on this one in a hangout / chat, been holding off here

**Comment by maxbates** [comment]
No one has made this pros-cons document, so we should actually do this for sprint 2. hard to assess Duncan's library thing without it.

**Comment by IsaacLuo** [comment]
I prefer SVG, it works perfect on a 4k/5k screen.

**Comment by dchandran** [comment]
Using HTML/CSS for first iteration. After Feb, we will redo the UI if necessary
