### ISSUE TITLE
Plan example plugin with front-end and back-end

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#70]
Front-end: widget that has an input box, a run button, and a message box
Back-end: node runs in the server, searches for the input, and returns the result as a string

**Comment by maxbates** [comment]
@dchandran can you describe this somewhere?

**Comment by dchandran** [comment]
#121 has a couple of example back-end plugins
Onion integration will be the first front-end plugin (which is another issue)
