### ISSUE TITLE
Sequence Detail View fails to come up with a part in search view selected.

### ISSUE THREAD

**Issue by joseph-schaeffer** [autodesk-bionano/genome-designer#746]
### URL
https://geneticconstructor.bionano.autodesk.com/project/project-debade3a-d014-405a-8468-5a995794afaa
### Expected Behavior
I clicked on a part in the part library, then on Sequence Detail View. I expected to see the sequence detail view.
### Actual Behavior (please include screenshot)
![image](https://cloud.githubusercontent.com/assets/9203940/18020758/0aa823f2-6b98-11e6-8e35-4338f5b51fe6.png)
### Steps to reproduce the problem
From an empty project, no constructs, I searched for "promoter", clicked on BBa_K1045014, then clicked on Sequence Detail View.  Got the above message. It wasn't specific to the particular item selected in the search view, many others (all I tried) gave the same issue. Adding a part to the construct, then clicking on the part was able to bring up Sequence Detail View ok. Not sure if that option (Sequence Detail View) is supposed to be disabled when a part is selected but not in the canvas, or if it's something else.

**Comment by cojofra** [comment]
@duncanmeech could you look at this? I just followed joseph steps and got exactly the same

**Comment by maxbates** [comment]
~~it seems there is no sequence assigned to the part until it is actually brought it (there is a difference between viewing the part and importing it into your project, the latter actually saves the sequence). we have support for sequence downloads, so can add one of those in /inventory/igem/parseResults.js to parseFullResult()~~ Sequence should be saved in L86 of `/inventory/igem/parseResults.js`...

**Comment by duncanmeech** [comment]
Resolved in commit to sequence viewer ( f95924ebaa451690f9dbacc10e4f17e6762e899b )
However, the bug will persist in the EGF details viewer. @maxbates will need to address issues with window.constructor.api.focus.focusGetBlockRange() when there is a forced block focused i.e. a search result in the inspector.

**Comment by maxbates** [comment]
new issue @duncanmeech ?
