### ISSUE TITLE
Enable the top-level construct triangle

### ISSUE THREAD

**Issue by cojofra** [autodesk-bionano/genome-designer#761]
<p>Currently, the large colorful triangle above a construct has no function.&nbsp;</p><p>We want to re-enable that for better usability.</p>

Functional Spec:
<p style="color: rgb(51, 51, 51);">The large, colorful triangle above every top-level construct should:</p><ol style="color: rgb(51, 51, 51);"><li>Allow the user to collapse the construct to show just the top level hierarchy);</li></ol>

Mockups:
![Screen_Shot_2016-09-09_at_11_41_59_AM.png](https://d1wgsi1t3wetrk.cloudfront.net/719c9173e05c124fd98b0b21b0f900435fe0d917.png?Expires=1504982579&Signature=dKI2SPtRttOjrbc~wy-QzPxyFhJRkNDYrn6Mk~tJB8GD2nrhXSy77YW5WigCL6ai6L1LN5SZLz1HVJajVKDG0MAnl~h6HvkD2TPlHmt3WYa6xVvXdd~eZcM1wGQDyD1bZIS~aNcLq2Kt16Eyougiu4e1g69ndMzRz5SprLQm-7kiK5bxZfiAtpJpAQhfIlUX9zoRqNft5vu9DB~dfkkSDEPwRnGpeUmRv7QU98JviT2WFDREhmQqoggcs3yc1znUJL3gQfYi6k6J87dWBkUtvQ~thLin9bi9MLj57PL5fCufxafCuZV4cl7VqxxWdHuf7NSNA36u8XJl30NL8pJa-w__&Key-Pair-Id=APKAJZAZ62TYGJ5PA7LA)

**Comment by duncanmeech** [comment]
Making a separate card for moving constructs around

**Comment by cojofra** [comment]
@duncanmeech is this done?
