### ISSUE TITLE
Inline text editing

### ISSUE THREAD

**Issue by cojofra** [autodesk-bionano/genome-designer#763]
<p>Currently, users have a hard time to edit title and description. The current UI does not always come into focus correctly and many online tools have inline editing capabilities so it is somewhat expected these days.</p><p><br></p>

<p style="color: rgb(51, 51, 51);">In addition to editing in the Inspector panel, the user should be able to edit text in situ in the following areas of the canvas:</p><ol style="color: rgb(51, 51, 51);"><li>The project name and description</li><li>Top level construct names</li><li>Blocks</li></ol>

**Comment by cojofra** [comment]
we'll do blocks later after the re-design

**Comment by maxbates** [comment]
I believe there is already a component which handles this. `InputSimple`
