### ISSUE TITLE
Make Onion modular

### ISSUE THREAD

**Issue by autodesk-bionano** [autodesk-bionano/genome-designer#8]
Decide how Onion will integrate into the rest of the app. Make Onion modular in order to fit this role.

**Comment by maxbates** [comment]
@IsaacLuo it might be helpful to make a wiki page in this repo describing what we takled about yesterday i.e. requirements for onion, data models, flows/ functions to support and whether they can just be called from python

**Comment by IsaacLuo** [comment]
Where should I create the wiki page, google document or Github wiki?

**Comment by jlachoff** [comment]
Removed UX label, as the design work for this task has been completed to an adequate level in Sprint 1. I propose we make a new task for continued refinement of the UX when the team is ready for that.

**Comment by IsaacLuo** [comment]
Designing it, going to make plasmid viewer as an individual module, which can be embedded in any DOM.

**Comment by maxbates** [comment]
https://github.com/Edinburgh-Genome-Foundry/genome-designer

**Comment by maxbates** [comment]
see also #83 and #16 ... closing this as it is vague and broad.
