### ISSUE TITLE
Onion - should it use its own data structure or adopt the genome designer's

### ISSUE THREAD

**Issue by dchandran** [autodesk-bionano/genome-designer#83]
Discuss Pros and Cons of each.

**Comment by maxbates** [comment]
Should adapt! 
- It needs to support some sort of hierarchical visualization, which our data format is essentially built to do, and is fairly simple
- Simplifies server communication greatly
- changes to data model should simplify this process

Todos:
- How to handle blocks without sequence - size, style, etc.
- Need to figure out how python functions will run on our server, or where they should exist.

**Comment by maxbates** [comment]
(Closed on accident)

**Comment by maxbates** [comment]
Decision is that short term onion will not persist local data, and will convert dgenome designer's format to its local format as needed.
