### ISSUE TITLE
the deal with part referencing

### ISSUE THREAD

**Issue by maxbates** [autodesk-bionano/genome-designer#834]
can't reference other parts. e.g. SBOL is highly referential

you can have a source, and you can look at parents. but is that enough?

we likely want non-static references

might be easier with DB if parts are their own entries. downside: computing a whole project much slower (unless list all blocks in a project off the bat)

**Comment by cojofra** [comment]
is this a note or a task?

**Comment by maxbates** [comment]
note. Will affect a ton of stuff. Will come up in context of several extensions / other formats we're looking at.

**Comment by cojofra** [comment]
mind if I put that into prodpad and close this?
