### ISSUE TITLE
Ability to download single order constructs

### ISSUE THREAD

**Issue by maxbates** [autodesk-bionano/genome-designer#874]

**Comment by cojofra** [comment]
@maxbates is this going to be taken care of with the new download functionality? or is this a sep task?

**Comment by maxbates** [comment]
already supported, but this is in the order modal, no affordance to do it

**Comment by cojofra** [comment]
sorry what does the last part mean?

**Comment by maxbates** [comment]
there is not e.g. a button

**Comment by cojofra** [comment]
got it

**Comment by cojofra** [comment]
may fold into ordering re-design
