### ISSUE TITLE
List yeast-fab services we need to support

### ISSUE THREAD

**Issue by autodesk-bionano** [autodesk-bionano/genome-designer#9]

**Comment by maxbates** [comment]
@IsaacLuo Is there a google doc or something for these? I'd also like to go through the need for the elaborate setup of server communication, and see if it can be simplified

**Comment by IsaacLuo** [comment]
https://docs.google.com/document/d/1gNpW4NIdhRaqvFMhBj86OVdTW4eUbqCVAWvx7k28_TY/edit?usp=sharing

We are planning to use Tecan and other automatic machine to do the rest part of yeastfab, so there will be new requirements later.
