### ISSUE TITLE
Insert DNA sequence content persists across blocks

### ISSUE THREAD

**Issue by cojofra** [autodesk-bionano/genome-designer#905]
Screencast:
https://drive.google.com/open?id=0BzUjRX4AzyD8YWkyZU9LZndYNHM

Recreate:
Drag blocks into a new construct
Add sequence to the first block
Click on add sequence for the second block - it now shows the sequence from the first block. it should not show anything.
The block from the first sequence shows nothing (most of the time) although it should show the sequence.

sequence viewer shows information correctly.

**Comment by maxbates** [comment]
This may be part of a larger issue with the way we handle modals - they are mounted and technically always in the app, but probably should only be in the app when they are actually called, and unmount when they are closed. Can we create a modal wrapper which does this @duncanmeech ?
