### ISSUE TITLE
Viewer jumps back to the beginning of the construct when selecting a different variant in a list block

### ISSUE THREAD

**Issue by cojofra** [autodesk-bionano/genome-designer#975]
Reproduce:
 - Select a list block construct
 - Open the sequence viewer and scroll to a combinatorial part - it has to be outside of the sequence that is visible in the viewer at first
 - For the block in question - select a different variant
 - Sequence viewer snaps back to original sequence

Expected behaviour:
 - block contents gets swapped in place

**Comment by cojofra** [comment]
@duncanmeech do you think its possible to look into this before SBB? (next Tuesday)

**Comment by duncanmeech** [comment]
Address in this commit in sequence viewer, although I need to review the FOCUS_BLOCK_OPTION event with Max since it appears a little flaky.

https://github.com/duncanmeech/sequence-viewer/commit/9b6bf8468e0cb1e798095f551648180f68e9e89e
